### ISSUE TITLE
Can only pipe to one destination

### ISSUE THREAD

**Issue by coreyfarrell** [streamxorg/streamx#15]
I'm not sure if this will be considered a bug, known limitation or feature request:

```js
'use strict';

const fs = require('fs');
const streamx = require('streamx');
const stream = require('readable-stream');

function tee(stream, filename) {
	try {
		stream.pipe(process.stdout);
		stream.pipe(fs.createWriteStream(filename));
		streamx.Readable.from(['write to: ', filename, '\n']).pipe(stream);
	} catch (error) {
		console.error('*** error:', error.message);
	}
}

tee(new streamx.Transform(), 'streamx.txt');
tee(new stream.PassThrough(), 'readable-stream.txt');
```

After running this script you will see:
```
*** error: Can only pipe to one destination
write to: readable-stream.txt
```

Additionally `write to: readable-stream.txt\n` is saved to readable-stream.txt.

**Comment by mafintosh** [comment]
Haha :) That's a feature, to keep it simple. We should support a TeeStream for this though

``` js
const t = tee(readStream)
t.clone().pipe(writeStream)
t.clone().pipe(writeStream)
```

**Comment by phated** [comment]
We currently use https://www.npmjs.com/package/cloneable-readable inside gulp, but it would be ideal to have a TeeStream in streamx like described.

**Comment by mafintosh** [comment]
I just wrote this https://github.com/mafintosh/teex

Would that work for this?

teex currently does *not* destroy the source readable if any of the tee'd ones are destroyed.
If that's something we need I can add an option for that.
