### ISSUE TITLE
Add pipeline function

### ISSUE THREAD

**Issue by Frando** [streamxorg/streamx#17]
Node streams, since Node 10, have a [`pipeline`](https://nodejs.org/api/stream.html#stream_stream_pipeline_source_transforms_destination_callback) function that allows to easily set up a stream pipeline, with a final callback called in case of errors.

I suggest to add and export such a `pipeline` function to streamx, to make it straightforward to port code that uses this from `stream` to `streamx`.

**Comment by mafintosh** [comment]
Ya, I just discussed doing that with @emilbayes actually.

**Comment by phated** [comment]
@mafintosh did this ever get added? We recommend all gulp users pipe stuff with pipeline (and it integrates well with our task system).

**Comment by mafintosh** [comment]
Not yet, but I’ll prio that since it’s a good idea

**Comment by martinheidegger** [comment]
Found its way through #37 with `v2.10.0`
