### ISSUE TITLE
Unexpected event ordering

### ISSUE THREAD

**Issue by coreyfarrell** [streamxorg/streamx#40]
Create `script.js`:
```js
'use strict';

const {Readable: {from}} = require(process.argv[2]);
const {PassThrough} = require(process.argv[3]);
const {pipeline} = require(process.argv[4]);

var write = new PassThrough({objectMode: true});
var source = from(['a', 'b']);

write.on('readable', function () {
  while (this.read()) {
    console.log('read');
  }
});

pipeline([source, write], function (err) {
  if (err) {
    console.error(err);
    process.exit(1);
  }

  console.log('pipeline done');
})
```

Now install `streamx` and `readable-stream@3`.  Running with different argument combinations will show compatibility.  In particular `node script.js streamx streamx stream` prints:
```
pipeline done
read
read
```

This order seems wrong and only happens if `Readable.from` and `PassThrough` are both from `streamx`.  Using `stream` or `readable-stream` for either/both of these produces the expected output order:
```
read
read
pipeline done
```

**Comment by mafintosh** [comment]
@coreyfarrell the order of the reads on the FINAL stream in a pipeline are not ordered in anyway compared to the call of the pipeline callback, both for streamx and core.

The callback fires when the WRITABLE side of the final stream is done.

Let me know if that makes sense or if I misunderstood.

**Comment by coreyfarrell** [comment]
I don't understand how the `pipeline` done callback can/should be run when data is still being pipelined?  In the `node script.js streamx streamx stream` case the pipeline done callback is run before the `write.on('end')` event dispatches.

**Comment by mafintosh** [comment]
writable.on('end') means the READABLE side is done. your pipeline above does not capture the readable side of the writable stream since it's the last stream, both for core and x.

If you wanna test the write ordering you need to do:

```
new Writable({
  write (data, cb) {
    console.log('wrote')
    cb()
  }
})
```

instead of a passthrough stream
