### ISSUE TITLE
Consider changing `process.nextTick` to `queueMicrotask`

### ISSUE THREAD

**Issue by feross** [streamxorg/streamx#42]
Browserify/Webpack will replace `process.nextTick` with a very inefficient shim which uses `setTimeout(..., 0)`. Have you considered using `queueMicrotask` instead?

If you're concerned about browser support, I have a shim here: https://github.com/feross/queue-microtask

**Comment by mafintosh** [comment]
Yea I’m moving to that in the next major which will also have promise support for the stream handlers :)
