### ISSUE TITLE
how does pause work?

### ISSUE THREAD

**Issue by dominictarr** [streamxorg/streamx#50]
I'm trying to use streamx to reimplement net directly (to use tcp on other platforms)
in node's net, socket overwrites Duplex.pause and calls `uv_tcp_read_stop`
https://github.com/nodejs/node/blob/master/lib/net.js#L616-L627

this seems correct, so I probably want to do that with streamx,
which provides pause, but does not seem to call pause anywhere.

it looks like streamx might be oriented towards a read/pull type interface
Is there a way to implement an flow/stop style stream?

**Comment by mafintosh** [comment]
We can just add a _pause and _resume hook you can impl

**Comment by mafintosh** [comment]
Actually misunderstood you, this is already supported.

```js
// when push is false, pause your source
onnewtcpread (data) {
  if (!this.push(data)) {
    this._stopped = true
    uv_tcp_read_stop()
  }
}

// read is called when the user wants more data
_read (cb) {
  if (this._stopped) {
    this._stopped = false
    uc_tcp_read_start()
  }
  cb(null)
}
```

**Comment by dominictarr** [comment]
aha great thanks! I didn't know about the push(data) return value!

**Comment by mafintosh** [comment]
Nice!

**Comment by dominictarr** [comment]
because this depends on the return value of push/write it doesn't pause without writing data.
I added this, so I could test it, but can see that it doesn't actually get called by streamx internally. 
```
  pause () {
    Duplex.prototype.pause.call(this)
    //send a ReadStop but do not wait for a confirmation.
    //ipc is async, but it's ordered,
    if(this._flowing) {
      this._flowing = false
      this._pause()
    }
    return this
  }
  resume () {
    Duplex.prototype.resume.call(this)
    //send a ReadStop but do not wait for a confirmation.
    //ipc is async, but it's ordered, 
    if(!this._flowing) { 
      this._flowing = true
      this._resume()
    }
    return this
  }
```
propagating pause only on the return value of write is a historical pattern from unix fs but is awkward in a non-blocking enviroment because it means that pause state cannot be propagated down a pipeline synchronously so every stream needs to grow a queue, especially since a write/push is always queued. It means that if you have a length N pipeline then it takes N writes to propagate the pause state back to the source.

**Comment by mafintosh** [comment]
Yep, the `push(data) === false`, is the only pause signal there is atm - all methods just signal the state machine. You can change the highWaterMark if you want when making the stream.
