### ISSUE TITLE
_read call triggered by write?

### ISSUE THREAD

**Issue by dominictarr** [streamxorg/streamx#51]
so I have a duplex stream (implementing tcp directly) and I have mock based tests.
I couldn't figure out why _read wasn't getting called because it was in another test.
but then I remembered that this sort of stream starts out paused and starts flowing when piped or a data listener is set.

but that meant the other test was wrong!

```
var {Duplex} = require('streamx')

class Socket extends Duplex {
  constructor (name) {
    super()
    this.name = name
  }
  _read () {
    console.log(this.name, "calls _read")
  }
}

var socket = new Socket('no-write')

var socket2 = new Socket('on-data')

socket2.on('data', function () {})

var socket3 = new Socket('write!')

socket3.write()
```
output:
```
on-data calls _read
write! calls _read
```
`"write!"` should not have called _read because there was no place to send the data. Or, no-write (which also doesn't have 'data' listener) should have called it, but a write call should not trigger a read.

**Comment by mafintosh** [comment]
It’s because the write opens the duplex state machine. The duplex state machine then checks if it has room in the read buffer. It does, so it calls _read to notify you about that, so you can push some data to it. Once the buffer is full, it’ll wait for you to drain it before calling _read again

**Comment by dominictarr** [comment]
is that duplex state machine documented or specified anywhere?

hmm, on that note, I see from tests/backpressure.js (and the docs) that any non-buffer is interpreted as worth 1024 bytes, so back pressure gets triggered once the default size 16k buffer is full... if it's in the tests can that be taken as specification?

**Comment by mafintosh** [comment]
The readme specifies most of the behaviour, including the buffer size stuff. Anything the tests specifies can be taken as a spec as well. Feel free to PR clarifications to the readme if something can be more clear.

**Comment by dominictarr** [comment]
but what do you mean by the duplex state machine? is that the update function?

**Comment by mafintosh** [comment]
The read stream has the following state machine

```
open -> read -> read -> read  ... -> end -> destroy
```

The write stream:

```
open -> write -> write -> write ... -> final -> destroy
```

The duplex combines the two

```
            -> read -> read -> read ... -> end
open  +                                                           + destroy
            -> write -> write -> write ... -> final
```

**Comment by dominictarr** [comment]
I'm assuming you don't mean 3 read events you mean at least one?
I guess it has to call _read at least once, but _write doesn't get called at all if the stream ends immediately.

I find that regular language syntax works well here
so readable: `_open _read+ _end _destroy` (space implies a sequence)
and writable `_open _write* _final _destroy`

unfortunately with this syntax there isn't an easy way two sequences merged in parallel. That wouldn't be very useful for describing a parser, which is the source of this syntax.

**Comment by mafintosh** [comment]
Yea that looks correct to me. A thing to add is that the _end and _final only happen if the stream isn't interrupted by a .destroy() call, then it does straight to _destroy when all currently running _reads and _writes are done.

**Comment by dominictarr** [comment]
really, I if destroy is called it should just drop any currently running reads/writes, which is consistent with tcp RST packet.

**Comment by mafintosh** [comment]
That what it does, it waits for you to call the cb of any running write/read and clears all future write/reads.
