### ISSUE TITLE
Readable[Symbol.asyncIterator] does not signal done

### ISSUE THREAD

**Issue by ThaUnknown** [streamxorg/streamx#55]
`Readable[Symbol.asyncIterator]` does not return an object of `{ done: true, value: null }` when the stream finishes, instead it hangs the promise indefinitely, even the last successfully read iteration says the stream is not done

My code:
```js
const { Readable } = require('streamx')

ReadableStream.prototype[Symbol.asyncIterator] = async function* () {
  const reader = this.getReader()
  let last = reader.read()
  while (1) {
    const temp = last
    last = reader.read()
    yield (await temp).value || null
  }
}

function BlobReadStream (blob, opts = {}){
  return Readable.from(blob.stream(), opts)
}
// ...
const stream = BlobReadStream(blob)
const asyncIterator = stream[Symbol.asyncIterator]()

let data
while (data){
  data = (await asyncIterator.next()).value
  console.log(data) // will never print null/undefined
}
```

the issue here seems to lay in passing null in Readable.from's iterator, but passing undefined isn't allowed in Node's readablestream spec, since it only allows Buffer, String or null

**Comment by mafintosh** [comment]
I’m not sure what you mean. Can you share a simple test case I can run (in nodejs preferred) that illustrates the problem?

**Comment by ThaUnknown** [comment]
@mafintosh 
```js
const { Readable } = require('streamx')

async function test() {
  const obj = {
    [Symbol.asyncIterator]: async function* () {
      yield new Uint8Array([1, 2, 3, 4])
    }
  }
  const stream = Readable.from(obj)
  const iterator = stream[Symbol.asyncIterator]()
  let value = true
  while (value) {
    value = (await iterator.next()).value
    console.log(value)
  }
  console.log('this is never reached')
}

test().then(() => console.log('done'))
```

**Comment by mafintosh** [comment]
Thanks!

Could be boiled down to the following test case, https://github.com/streamxorg/streamx/blob/master/test/async-iterator.js#L174-L188

There was an uncaught in from that promises swallowed, but fixed in latest.

**Comment by ThaUnknown** [comment]
> Thanks!
> 
> Could be boiled down to the following test case, https://github.com/streamxorg/streamx/blob/master/test/async-iterator.js#L174-L188
> 
> There was an uncaught in from that promises swallowed, but fixed in latest.

Great, happy to help, sorry I couldn't find the underlying issue, don't really understand the full structure of streams
