### ISSUE TITLE
AsyncIterator in a Duplex stream never ends

### ISSUE THREAD

**Issue by tinchoz49** [streamxorg/streamx#62]
I was trying to iterate over the data in a Duplex stream since extends from Readable but it never ends properly.

I think the problem is that in a Duplex stream the `close` event for the Readable side never happen. Is that the correct behavior in this case?

```javascript
import { Duplex } from 'streamx'

;(async () => {
  const stream = new Duplex({
    read (cb) {
      this.push('test')
      this.push(null)
      cb()
    }
  })

  for await (const chunk of stream) {
    console.log(chunk)
  }

  console.log('done') // never get this
})()
```

**Comment by mafintosh** [comment]
I'd say, that's a bug on your end since you are not ending the writable side of the stream.

**Comment by mafintosh** [comment]
ie, if you add stream.end() that works yea?
