### ISSUE TITLE
duplex never fires end

### ISSUE THREAD

**Issue by ThaUnknown** [streamxorg/streamx#65]
duplex never fires the end event? I assume this is because it inherits from writablestate which never fires the event?

**Comment by mafintosh** [comment]
all events fire when their condition is reached. for end thats when the readable side of the stream has ended and all data has been drained

**Comment by mafintosh** [comment]
Feel free to reopen with an example you are confused by or a failing test case if you believe there is a bug

**Comment by ThaUnknown** [comment]
Oh I see, I must be missing something because this event never fires :/ https://github.com/ThaUnknown/simple-websocket/blob/streamx/test/stream.js#L20-L23

**Comment by ThaUnknown** [comment]
I guess maybe the issue is that calling .end() never ends the readable state?

**Comment by mafintosh** [comment]
end fires when you push(null) and have drained all data. .end() fires finish when done

**Comment by ThaUnknown** [comment]
> end fires when you push(null) and have drained all data. .end() fires finish when done

ah, then is there a way to check if a stream is finished but not ended? I'm getting dizzy from all the bitwise operators

**Comment by ThaUnknown** [comment]
> drained

hm, then I don't really know what's wrong here, here's roughly what I'm doing:

```js
class Socket extends Duplex {
  _destroy (cb) {
    if (!this._readableState.ended) this.push(null)
    if (!this._writableState.ended) this.end()
    cb()
  }

  _write (data, cb) {
    this.push(data)
    cb()
  }
}
const stream = new Socket()

stream.on('data', () => {
  console.log('data')
  stream.end()
})
stream.on('finish', () => {
  console.log('finished')
})
stream.on('end', () => {
  console.log('end') // never runs
})
stream.write('abc')
```

**Comment by ThaUnknown** [comment]
@mafintosh FYI I don't have perms to re-open this issue

**Comment by mafintosh** [comment]
You cant push during destroy. Also dont rely on the the understore state, that’s a sign you are doing it wrong.

If I understand what you are trying to do you need a final handler. That one is run when the end() is flushing (the readme says this also btw)

```
_final (cb) {
  this.push(null)
  cb(null)
}
```

**Comment by ThaUnknown** [comment]
thanks,

yeah I realise anything relying o _ is bad as _ prefix is the old way of saying "private field", but as per the email I sent you I'm re-writing existing packages from node's readable-stream to streamx

**Comment by mafintosh** [comment]
.destroy will not fire any finish or end events. destroy tears down the stream, emitting error (if you passed one) and then close, then the stream is fully dead, like described in the readme.

**Comment by ThaUnknown** [comment]
> .destroy will not fire any finish or end events. destroy tears down the stream, emitting error (if you passed one) and then close, then the stream is fully dead, like described in the readme.

so there's no way to gracefully end a stream, while emitting an error?

**Comment by mafintosh** [comment]
not without doing in from the end event etc. if you are relying on that, i would rethink the stream architecture from personal experience - ie errors are errors

**Comment by ThaUnknown** [comment]
> not without doing in from the end event etc. if you are relying on that, i would rethink the stream architecture from personal experience - ie errors are errors

yeah the issue i run into is not making modules from scratch using streamx, but migrating existing modules to streamx, I emailed you about this once, because i'm struggling like crazy to make webtorrent drop readable and use streamx

**Comment by mafintosh** [comment]
Happy to help you through a simple example, if you have one.

**Comment by ThaUnknown** [comment]
> Happy to help you through a simple example, if you have one.

i... honestly don't even know whats wrong, i have 2 duplex streams, both can close at any time, if one of them closes, both should end, but i either get them to end correctly, or send data across, not both

**Comment by ThaUnknown** [comment]
I ended up doing this, but its mostly patching around streamx rather than implementing it
